### ISSUE TITLE
[Django] Error (EXTERNAL IP): /pics/в

### ISSUE THREAD

**Issue by Alerion** [djbook-ru/djbookru#73]
Traceback (most recent call last):

 File "/usr/local/lib/python2.6/dist-packages/django/core/handlers/base.py", line 100, in get_response
   response = callback(request, _callback_args, *_callback_kwargs)

 File "/usr/local/lib/python2.6/dist-packages/django/views/static.py", line 51, in serve
   if os.path.isdir(fullpath):

 File "/usr/lib/python2.6/genericpath.py", line 41, in isdir
   st = os.stat(s)

UnicodeEncodeError: 'ascii' codec can't encode character u'\u0432' in position 42: ordinal not in range(128)

**Comment by ynikitenko** [comment]
In Django documentation it's written that this may be connected to Apache settings.
https://docs.djangoproject.com/en/1.4/howto/deployment/modpython/#if-you-get-a-unicodeencodeerror
"""To avoid these problems, the environment used to start Apache should contain settings analogous to the following:
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'
"""
